/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.consultaprodutos;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Luiz
 */
public class frmConsultadePreços extends javax.swing.JFrame {

    /**
     * Creates new form ConsultadePreços
     */
    public frmConsultadePreços() {
        initComponents();
         lbl_descrição.setText("");
                    lbl_Estoque.setText("");
                    lbl_Estoque_Estoque_db.setText("");
                    lbl_Preço.setText("");
                    lbl_Preço_db.setText("");
                    lbl_descricao_bd.setText("");
                    lbl_erro.setText("");
        tb_CodigoaPesquisar.setText("");
                lbl_TagR$.setText("");
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_desciritvo = new javax.swing.JLabel();
        lbl_descricao_bd = new javax.swing.JLabel();
        lbl_Preço = new javax.swing.JLabel();
        lbl_Preço_db = new javax.swing.JLabel();
        lbl_Estoque = new javax.swing.JLabel();
        lbl_Estoque_Estoque_db = new javax.swing.JLabel();
        lbl_descrição = new javax.swing.JLabel();
        tb_CodigoaPesquisar = new javax.swing.JTextField();
        lbl_erro = new javax.swing.JLabel();
        lbl_TagR$ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Preços");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lbl_desciritvo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_desciritvo.setText("Insira o código a pesquisar:");

        lbl_descricao_bd.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_descricao_bd.setText("jLabel2");

        lbl_Preço.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        lbl_Preço.setText("Preço:");

        lbl_Preço_db.setFont(new java.awt.Font("Arial", 0, 124)); // NOI18N
        lbl_Preço_db.setText("Preço");

        lbl_Estoque.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Estoque.setText("Estoque:");

        lbl_Estoque_Estoque_db.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Estoque_Estoque_db.setText("jLabel6");

        lbl_descrição.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_descrição.setText("jLabel1");

        tb_CodigoaPesquisar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tb_CodigoaPesquisar.setAutoscrolls(false);
        tb_CodigoaPesquisar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tb_CodigoaPesquisarCaretUpdate(evt);
            }
        });
        tb_CodigoaPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tb_CodigoaPesquisarKeyTyped(evt);
            }
        });

        lbl_erro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_erro.setText("jLabel2");

        lbl_TagR$.setFont(new java.awt.Font("Arial", 0, 124)); // NOI18N
        lbl_TagR$.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Estoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Estoque_Estoque_db))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Preço)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_TagR$)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Preço_db))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_descrição)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_descricao_bd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_desciritvo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tb_CodigoaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbl_erro, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb_CodigoaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_desciritvo))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descricao_bd)
                    .addComponent(lbl_descrição))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Preço)
                    .addComponent(lbl_TagR$)
                    .addComponent(lbl_Preço_db))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Estoque)
                    .addComponent(lbl_Estoque_Estoque_db))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_erro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_CodigoaPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisarKeyTyped
String caracteres="0987654321";
if(!caracteres.contains(evt.getKeyChar()+"")){
evt.consume();
  }                        

    }//GEN-LAST:event_tb_CodigoaPesquisarKeyTyped

    private void tb_CodigoaPesquisarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisarCaretUpdate
rodarConsulta();
    }//GEN-LAST:event_tb_CodigoaPesquisarCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultadePreços.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultadePreços.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultadePreços.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultadePreços.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConsultadePreços().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Estoque;
    private javax.swing.JLabel lbl_Estoque_Estoque_db;
    private javax.swing.JLabel lbl_Preço;
    private javax.swing.JLabel lbl_Preço_db;
    private javax.swing.JLabel lbl_TagR$;
    private javax.swing.JLabel lbl_desciritvo;
    private javax.swing.JLabel lbl_descricao_bd;
    private javax.swing.JLabel lbl_descrição;
    private javax.swing.JLabel lbl_erro;
    private javax.swing.JTextField tb_CodigoaPesquisar;
    // End of variables declaration//GEN-END:variables


public void rodarConsulta(){
      
        ConsultaProdutos consulta = new ConsultaProdutos();
        List<Produtos> resultado = new ArrayList<>();
        resultado = consulta.ConsultarProduto();
        //System.out.print("\nTemos "+resultado.size()+" registros");
        lbl_Estoque_Estoque_db.setText("");
        lbl_Preço.setText("");
        lbl_descricao_bd.setText("");
        int codigopesquisado;
       boolean sucesso = false;
       
        codigopesquisado = Integer.valueOf(tb_CodigoaPesquisar.getText());




        
        if (codigopesquisado>0){ 
                for (int i = 0 ; i<resultado.size();i++)
                {
                    if (Integer.valueOf(resultado.get(i).getCodigo())== codigopesquisado){
                        sucesso=true;
                        lbl_erro.setText("");
                        lbl_descrição.setText("Produto:");
                        lbl_Estoque.setText("Estoque:");
                        lbl_Preço.setText("Preço:");
                        lbl_TagR$.setText("R$");
                        lbl_Estoque_Estoque_db.setText(String.valueOf(resultado.get(i).getEstoque()));
                        DecimalFormat df = new DecimalFormat("0.00");
                        
                        
                        lbl_Preço_db.setText(String.valueOf(df.format(resultado.get(i).getPreco())));
                        lbl_descricao_bd.setText(String.valueOf(resultado.get(i).getNome()));
                       
                    //System.out.print("\n "+String.valueOf(resultado.get(i).getNome()));
                                break;
                } 
                    
                }
                if (sucesso==false){
                        
                    lbl_erro.setText("Não encontrei produto com o código "+codigopesquisado);
                    lbl_descrição.setText("");
                    lbl_Estoque.setText("");
                    lbl_Estoque_Estoque_db.setText("");
                    lbl_Preço.setText("");
                    lbl_descricao_bd.setText("");
                    lbl_Preço_db.setText("");
                    lbl_TagR$.setText("");
                }
                 
        
        
        
       
}
}
}