/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.consultaprodutos;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
//import static sun.jvm.hotspot.HelloWorld.e;

/**
 *
 * @author Luiz
 */
public class frmConsultadePrecos extends javax.swing.JFrame {
         config objconfig = new config();
         public ConsultaProdutos consulta;
         public List<Produtos> resultado = new ArrayList<>();
         public int contador = 0;
         public String pesquisado;
//         public ArrayList listagemJtable;

    public frmConsultadePrecos() {
            // gravar();
            // ler();
    
     consulta = new ConsultaProdutos();
     resultado = consulta.ConsultarProduto();
     initComponents();
     painelCodigo.setVisible(true);
     
    //atualizadados();
                    lbl_descricao_bd.setText("");
                    lbl_Estoque.setText("");
                    lbl_Estoque_Estoque_db.setText("");
                    lbl_Preco.setText("");
                    lbl_Preco.setText("");
                    lbl_descricao_bd.setText("");
                    lbl_erro.setText("");
                    tb_CodigoaPesquisar.setText("");
                    lbl_R$.setText("");
                    tb_CodigoaPesquisar.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelComAbas = new javax.swing.JTabbedPane();
        painelCodigo = new javax.swing.JPanel();
        tb_CodigoaPesquisar = new javax.swing.JTextField();
        lbl_descricao_bd = new javax.swing.JLabel();
        lbl_R$ = new javax.swing.JLabel();
        lbl_Preco = new javax.swing.JLabel();
        lbl_Estoque = new javax.swing.JLabel();
        lbl_Estoque_Estoque_db = new javax.swing.JLabel();
        lbl_erro = new javax.swing.JLabel();
        lbl_descritivo = new javax.swing.JLabel();
        painelGeral = new javax.swing.JPanel();
        tb_CodigoaPesquisar1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        lbl_descritivo1 = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        menuAtualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa de produtos "+resultado.size()+" regsitros ");
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.black);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        painelComAbas.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        painelComAbas.setAutoscrolls(true);
        painelComAbas.setFocusCycleRoot(true);
        painelComAbas.setInheritsPopupMenu(true);
        painelComAbas.setMaximumSize(new java.awt.Dimension(1024, 768));

        painelCodigo.setBackground(new java.awt.Color(0, 0, 0));
        painelCodigo.setInheritsPopupMenu(true);
        painelCodigo.setMaximumSize(new java.awt.Dimension(1024, 768));
        painelCodigo.setPreferredSize(new java.awt.Dimension(1024, 768));

        tb_CodigoaPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        tb_CodigoaPesquisar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tb_CodigoaPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        tb_CodigoaPesquisar.setAutoscrolls(false);
        tb_CodigoaPesquisar.setSelectionStart(5);
        tb_CodigoaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_CodigoaPesquisarActionPerformed(evt);
            }
        });
        tb_CodigoaPesquisar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tb_CodigoaPesquisarPropertyChange(evt);
            }
        });
        tb_CodigoaPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tb_CodigoaPesquisarKeyReleased(evt);
            }
        });

        lbl_descricao_bd.setBackground(new java.awt.Color(102, 102, 0));
        lbl_descricao_bd.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_descricao_bd.setForeground(new java.awt.Color(255, 255, 0));
        lbl_descricao_bd.setText("Descrição do Produto");

        lbl_R$.setBackground(new java.awt.Color(0, 0, 0));
        lbl_R$.setFont(new java.awt.Font("Arial", 0, 190)); // NOI18N
        lbl_R$.setForeground(new java.awt.Color(255, 255, 0));
        lbl_R$.setText("$");

        lbl_Preco.setBackground(new java.awt.Color(0, 0, 204));
        lbl_Preco.setFont(new java.awt.Font("Arial", 0, 190)); // NOI18N
        lbl_Preco.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Preco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Preco.setText("Preco");

        lbl_Estoque.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Estoque.setForeground(new java.awt.Color(255, 255, 51));
        lbl_Estoque.setText("Estoque:");

        lbl_Estoque_Estoque_db.setBackground(new java.awt.Color(0, 51, 51));
        lbl_Estoque_Estoque_db.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Estoque_Estoque_db.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Estoque_Estoque_db.setText("ValorEstoque");

        lbl_erro.setBackground(new java.awt.Color(0, 51, 51));
        lbl_erro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_erro.setForeground(new java.awt.Color(255, 255, 0));
        lbl_erro.setText("Erro");

        lbl_descritivo.setBackground(new java.awt.Color(102, 102, 0));
        lbl_descritivo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_descritivo.setForeground(new java.awt.Color(255, 255, 0));
        lbl_descritivo.setText("Insira o código a pesquisar:");

        javax.swing.GroupLayout painelCodigoLayout = new javax.swing.GroupLayout(painelCodigo);
        painelCodigo.setLayout(painelCodigoLayout);
        painelCodigoLayout.setHorizontalGroup(
            painelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCodigoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_Estoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Estoque_Estoque_db))
                    .addGroup(painelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCodigoLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lbl_R$)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_Preco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(painelCodigoLayout.createSequentialGroup()
                            .addComponent(lbl_descritivo)
                            .addGap(18, 18, 18)
                            .addComponent(tb_CodigoaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(78, 78, 78))
                        .addComponent(lbl_descricao_bd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        painelCodigoLayout.setVerticalGroup(
            painelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCodigoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(painelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descritivo)
                    .addComponent(tb_CodigoaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_R$, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_descricao_bd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_erro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Estoque_Estoque_db)
                    .addComponent(lbl_Estoque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelComAbas.addTab("Código", null, painelCodigo, "Pesquisa por Código");

        painelGeral.setBackground(new java.awt.Color(0, 51, 51));
        painelGeral.setToolTipText("Consulta Geral");
        painelGeral.setName("painelGeral"); // NOI18N

        tb_CodigoaPesquisar1.setBackground(new java.awt.Color(153, 153, 153));
        tb_CodigoaPesquisar1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tb_CodigoaPesquisar1.setForeground(new java.awt.Color(255, 255, 255));
        tb_CodigoaPesquisar1.setAutoscrolls(false);
        tb_CodigoaPesquisar1.setSelectionStart(5);
        tb_CodigoaPesquisar1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tb_CodigoaPesquisar1CaretUpdate(evt);
            }
        });
        tb_CodigoaPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_CodigoaPesquisar1ActionPerformed(evt);
            }
        });
        tb_CodigoaPesquisar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tb_CodigoaPesquisar1PropertyChange(evt);
            }
        });
        tb_CodigoaPesquisar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tb_CodigoaPesquisar1KeyReleased(evt);
            }
        });

        jTableProdutos.setAutoCreateRowSorter(true);
        jTableProdutos.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código do Produto", "Descritivo ", "Preço", "Quantidade em Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableProdutos.setRowHeight(26);
        jScrollPane1.setViewportView(jTableProdutos);

        lbl_descritivo1.setBackground(new java.awt.Color(102, 102, 0));
        lbl_descritivo1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_descritivo1.setForeground(new java.awt.Color(255, 255, 0));
        lbl_descritivo1.setText("Insira parte da descrição do produto:");

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addComponent(lbl_descritivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_CodigoaPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descritivo1)
                    .addComponent(tb_CodigoaPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        painelComAbas.addTab("Descritivo", painelGeral);

        menu1.setText("Conexão");

        menuAtualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        menuAtualizar.setText("Atualizar");
        menuAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAtualizarActionPerformed(evt);
            }
        });
        menu1.add(menuAtualizar);

        menuPrincipal.add(menu1);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelComAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelComAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
        );

        painelComAbas.getAccessibleContext().setAccessibleName("Descritivo");

        setSize(new java.awt.Dimension(800, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAtualizarActionPerformed
        atualizadados();
    }//GEN-LAST:event_menuAtualizarActionPerformed

    private void tb_CodigoaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_CodigoaPesquisarActionPerformed

    private void tb_CodigoaPesquisarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_CodigoaPesquisarPropertyChange

    private void tb_CodigoaPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisarKeyReleased
      rodarConsulta();
    }//GEN-LAST:event_tb_CodigoaPesquisarKeyReleased

    private void tb_CodigoaPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_CodigoaPesquisar1ActionPerformed

    private void tb_CodigoaPesquisar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisar1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_CodigoaPesquisar1PropertyChange

    private void tb_CodigoaPesquisar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_CodigoaPesquisar1KeyReleased

    private void tb_CodigoaPesquisar1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tb_CodigoaPesquisar1CaretUpdate
        rodarConsultaGeral();        
    }//GEN-LAST:event_tb_CodigoaPesquisar1CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultadePrecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultadePrecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultadePrecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultadePrecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConsultadePrecos().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JLabel lbl_Estoque;
    private javax.swing.JLabel lbl_Estoque_Estoque_db;
    private javax.swing.JLabel lbl_Preco;
    private javax.swing.JLabel lbl_R$;
    private javax.swing.JLabel lbl_descricao_bd;
    private javax.swing.JLabel lbl_descritivo;
    private javax.swing.JLabel lbl_descritivo1;
    private javax.swing.JLabel lbl_erro;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuItem menuAtualizar;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel painelCodigo;
    private javax.swing.JTabbedPane painelComAbas;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JTextField tb_CodigoaPesquisar;
    private javax.swing.JTextField tb_CodigoaPesquisar1;
    // End of variables declaration//GEN-END:variables


public void rodarConsulta(){
    contador++;
            if(contador>100)
            {
                atualizadados();
                contador = 0;
            }
tb_CodigoaPesquisar.requestFocus();    
      if (tb_CodigoaPesquisar.getText().length()<5 && tb_CodigoaPesquisar.getText().length()>0)
      {        
       //System.out.print("\nTemos "+resultado.size()+" registros");
        lbl_Estoque_Estoque_db.setText("");
        lbl_Preco.setText("");
        lbl_descricao_bd.setText("");
        int codigopesquisado;
        boolean sucesso = false;
       codigopesquisado = Integer.valueOf(tb_CodigoaPesquisar.getText());
        if (codigopesquisado>0){ 
            
                for (int i = 0 ; i<resultado.size();i++)
                {
                    if (Integer.valueOf(resultado.get(i).getCodigo())== codigopesquisado){
                        sucesso=true;
                        lbl_erro.setText("");
                        lbl_descricao_bd.setText("Produto:");
                        lbl_Estoque.setText("Estoque:");
                        lbl_Preco.setText("Preco:");
                        lbl_R$.setText("$");
                        lbl_Estoque_Estoque_db.setText(String.valueOf(resultado.get(i).getEstoque()));
                        DecimalFormat df = new DecimalFormat("0.00");
                        lbl_Preco.setText(String.valueOf(df.format(resultado.get(i).getPreco())));
                        lbl_descricao_bd.setText(String.valueOf(resultado.get(i).getNome()));
                       
                    //System.out.print("\n "+String.valueOf(resultado.get(i).getNome()));
                                break;
                } 
                    
                }
                if (sucesso==false){
                        
                    lbl_erro.setText("Não encontrei produto com o código "+codigopesquisado);
                    limpatexto();
                }
                 
}
} else
      {
             lbl_erro.setText("Verifique o código digitado");   
             
             tb_CodigoaPesquisar.setText("");
             
     //impatexto();
      }         
}

public void rodarConsultaGeral(){
    pesquisado = tb_CodigoaPesquisar1.getText().toUpperCase();
    contador++;
    //System.out.println("\n Resultado size: "+resultado.size());
    if (resultado.size()>0){
        DefaultTableModel modelo = (DefaultTableModel)jTableProdutos.getModel();
        modelo.setNumRows(0);
        jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(420);
        jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableProdutos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableProdutos.setAutoCreateRowSorter(true);
        
        for(int i=0;i<=resultado.size()-1;i++){
             // System.out.println("\n "+pesquisado+" - "+resultado.get(i).getNome()+" - "+resultado.get(i).getCodigo());
           if (resultado.get(i).getCodigo().contains(pesquisado)||
                    resultado.get(i).getNome().contains(pesquisado)){   
            modelo.addRow(new Object[]{
            resultado.get(i).getCodigo(),
            resultado.get(i).getNome(),    
            resultado.get(i).getPreco(),
            resultado.get(i).getEstoque()
                    });
            }}}
            
            if(contador>100)
            {
                atualizadados();
                contador = 0;
            }
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTableProdutos.getModel());
        jTableProdutos.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        int columnIndexToSort = 1;
        sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        sorter.sort();
        tb_CodigoaPesquisar1.requestFocus();    
                }

                 


public void limpatexto()
{
                    //_CodigoaPesquisar.setText(" ");
                    lbl_descricao_bd.setText(" ");
                    
                    lbl_Estoque.setText(" ");
                    lbl_Estoque_Estoque_db.setText(" ");
                    lbl_Preco.setText(" ");
                    lbl_descricao_bd.setText(" ");
                    lbl_Preco.setText(" ");
                    lbl_R$.setText(" ");
                    tb_CodigoaPesquisar.requestFocus();
}

public void atualizadados()
{
    System.out.println("\nEntrou em atualizadados...");
lbl_erro.setText("Buscando produtos...!");
resultado = consulta.ConsultarProduto();
lbl_erro.setText("Registros atualizados!");
LocalDateTime localDateTime = LocalDateTime.now();
String Hora = String.valueOf(localDateTime.toLocalTime());
DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
String formattedDate = localDateTime.format(myFormatObj);
setTitle("Pesquisa de produtos "+resultado.size()+" registros - Atualizado em: "+formattedDate);
}

class config implements Serializable
{
String caminho,teste;    }


public void ler()
{
    try
    {
     FileInputStream arquivo = new FileInputStream("configura.txt");
     ObjectInputStream objentrada =new ObjectInputStream(arquivo);
     config dados = (config)objentrada.readObject();
     JOptionPane.showMessageDialog(null, "caminho "+dados.caminho);
}
    
    catch (Exception ex)
    {
               JOptionPane.showMessageDialog(null, ex);
    }
}
public void gravar()
{
    objconfig.caminho="C:\\teste";
    objconfig.teste="aaa";
        try {
          
           FileOutputStream arquivo = new FileOutputStream("configura.txt");
           ObjectOutputStream objsaida = new ObjectOutputStream(arquivo);
           objsaida.writeObject(objconfig);
           objsaida.flush();
            JOptionPane.showMessageDialog(null, "Gravei o arquivo de configurações");       
                   } catch (IOException ex) {
            //0ogger.getLogger(ConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }


}
}
